name: firestore_all
description: Plugin that wraps Firestore from `firebase` and `cloud_firestore` packages and expose them as a single API.
version: 0.1.0+1
author: Jaroslaw Butajlo <jaroslaw.butajlo@gmail.com>
homepage: https://github.com/jarekb123/firestore_all
issue_tracker: https://github.com/jarekb123/firestore_all/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ">=0.12.0 <0.13.0"
  firebase: ">=5.0.0 <5.1.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
